### PR TITLE
Password protect the whole aplication and notes deletion

### PR DESCRIPTION
**Pull request by WillBBHM**
#### What is it?
- [ ] Bugfix
- [x] Feature
- [ ] Codebase improvement

This is the link of the feature request :
[https://github.com/FossifyOrg/Notes/issues/17](https://github.com/FossifyOrg/Notes/issues/17)

#### Description of the changes and new features

- Added Password protect the whole aplication
- Added Password of the app protect notes deletion
- Added a new settings section to the settings menu, with a checkbox to enable or disable application password protection.
(Request user to create a password)

#### Screenshots

- New Settings "password" added in settings menu: 
Capture d'écran 2024-02-16 223609
- App protection at start:
Capture d'écran 2024-02-16 223652
- Notes deletion protection (after confirmation delete):
Capture d'écran 2024-02-16 223736

#### Acknowledgement
- [x] I read the [contribution guidelines](https://github.com/FossifyOrg/Notes/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by Aga-C** [comment]
Why haven't you did it similarly as it's done in other apps? Why new strings, new config items?

Check how it's done in Gallery:
- [Settings activity](https://github.com/FossifyOrg/Gallery/blob/master/app/src/main/kotlin/org/fossify/gallery/activities/SettingsActivity.kt#L397) ← take a look that no new items in config needs to be made since they are already in BaseConfig from Commons
- [Settings.xml](https://github.com/FossifyOrg/Gallery/blob/master/app/src/main/res/layout/activity_settings.xml#L700) ← see that all strings are currently defined in Commons, no need to create new ones
- [Main activity](https://github.com/FossifyOrg/Gallery/blob/master/app/src/main/kotlin/org/fossify/gallery/activities/MainActivity.kt#L244) ← also using logic from Commons, hiding whole app behind password is just few lines of code

BTW. In template there was `Fixes #` because GitHub will automatically close original issue after merging if this syntax is used. It makes our work easier, because we don't need to manually close issues then.

**Comment by WillBBHM** [comment]
The new configuration items and character strings were added because they weren't already there (as they're not a note but the application, I had to modify them slightly). As for the config, it's because the application remembers its passwords, but the application itself isn't a note, and I wanted the application to take the same form as the way notes are protected, to protect the application.

**Comment by Aga-C** [comment]
I know they weren't defined in Notes, but they are already in Commons, which is imported everywhere, and you can just use it. Look at the Gallery code I sent you, there's also a whole app blocked, and it's fully using things from Commons.

**Comment by WillBBHM** [comment]
As I'm still a computer science student, could you please help me implement it? Or at least guide me through it? With common. I'm going to try and implement it myself by looking at other applications.

**Comment by Aga-C** [comment]
Check links I've sent you a few comments before. They point exact lines of code.

**Comment by naveensingh** [comment]
> I'm still a computer science student, could you please help me implement it?

Thanks for your contribution but no. As Agni said above, check how it's done in other Fossify apps. 

We won't be "helping" people implement anything as that will invite more and more people who are beginning to learn Android development and helping people learn development is not the mission.

**Comment by WillBBHM** [comment]
I've almost finished re-implementing everything starting from Common and based on other Fossify applications, as well as those you've mentioned. I'm stuck on one last step, which is hiding the TextView for notes. I can't seem to replicate the behavior that hides the application in the same way as the Gallery Photo and File Storage application. What part of the code handles making it appear or disappear? Or what calls the lock view of the Text fragment on top?"

`override fun onCreate(savedInstanceState: Bundle?) {
        isMaterialActivity = true
        super.onCreate(savedInstanceState)
        setContentView(binding.root)
        appLaunched(BuildConfig.APPLICATION_ID)
        setupOptionsMenu()
        refreshMenuItems()

        updateMaterialActivityViews(binding.mainCoordinator, null, useTransparentNavigation = false, useTopSearchMenu = false)

        mIsPasswordProtectionPending = config.isAppPasswordProtectionOn

        if (savedInstanceState == null) {
            handleAppPasswordProtection {
                mWasProtectionHandled = it
                if (it) {
                    mIsPasswordProtectionPending = false
                } else {
                    finish()
                }
            }
        }

        searchQueryET = findViewById(org.fossify.commons.R.id.search_query)
        searchPrevBtn = findViewById(org.fossify.commons.R.id.search_previous)
        searchNextBtn = findViewById(org.fossify.commons.R.id.search_next)
        searchClearBtn = findViewById(org.fossify.commons.R.id.search_clear)

        val noteToOpen = intent.getLongExtra(OPEN_NOTE_ID, -1L)
        initViewPager(noteToOpen)
        binding.pagerTabStrip.drawFullUnderline = false
        val textSize = getPercentageFontSize()
        binding.pagerTabStrip.setTextSize(TypedValue.COMPLEX_UNIT_PX, textSize)
        binding.pagerTabStrip.layoutParams.height =
            (textSize + resources.getDimension(org.fossify.commons.R.dimen.medium_margin) * 2).toInt()
        (binding.pagerTabStrip.layoutParams as ViewPager.LayoutParams).isDecor = true

        val hasNoIntent = intent.action.isNullOrEmpty() && noteToOpen == -1L

        checkWhatsNewDialog()
        checkIntents(intent)

        storeStateVariables()
        if (config.showNotePicker && savedInstanceState == null && hasNoIntent) {
            displayOpenNoteDialog()
        }

        wasInit = true

        checkAppOnSDCard()
        setupSearchButtons()
    }`

**Pull request closed without merging**
